[theme]
base = "dark"
primaryColor = "#4D9FD1"
backgroundColor = "#0B1016"
secondaryBackgroundColor = "#121922"
textColor = "#EDF3F7"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
